### PR TITLE
Add docker multi arch images

### PR DESCRIPTION
**Pull request by bdovaz**
#146

### CODE REVIEW

**Comment by bdovaz** [comment]
@ahmadnassri bump!

Can you merge this, please?

**Review by ahmadnassri — APPROVED** [review]

**Comment by ahmadnassri** [comment]
indeed. I'm on a train heading to my office, will update it once I'm there

**Comment by bdovaz** [comment]
Reminder of that timeout issue

**Comment by ahmadnassri** [comment]
sorry for taking too long, I've been down with covid ... 

also, for whatever reason the builds get stuck on arm/v6 and arm/v7 (see [here](https://github.com/ahmadnassri/action-dependabot-auto-merge/actions/runs/3716187302/jobs/6302253261)) no matter how generous the time out is ...

I've now limited them to amd64 & arm64 just to keep this moving...

**Comment by bdovaz** [comment]
In my case its ok with arm64 the rest I added them to have more compatibility with arm.

You need to upload the new image to docker hub, right? The last one on registry right now is 2.6.3

**Comment by ahmadnassri** [comment]
use the gcr.io version: https://github.com/ahmadnassri/action-dependabot-auto-merge/pkgs/container/action-dependabot-auto-merge

**Comment by ahmadnassri** [comment]
I'm also working on v3 rewrite that doesn't use docker at all, and includes many improvements

**Pull request merged**
